// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protobuf-to-swift
//

import APIKit
import Foundation

/// hostに対しての同時接続数を制限したSession
final class SerialSession: Session {

    static let sharedSession = SerialSession()

    convenience init() {
        let config = URLSessionConfiguration.default
        config.httpMaximumConnectionsPerHost = 1
        let adapter = URLSessionAdapter(configuration: config)
        self.init(adapter: adapter)
    }

    func response<T: Request>(for request: T) async throws -> T.Response {
        let sessionTask: Wrapper<APIKit.SessionTask?> = Wrapper(nil)
        return try await withTaskCancellationHandler {
            try await withCheckedThrowingContinuation { continuation in
                sessionTask.value = send(request) { result in
                    switch result {
                    case let .success(response):
                        continuation.resume(returning: response)
                    case let .failure(error):
                        continuation.resume(throwing: error)
                    }
                }
            }
        } onCancel: {
            sessionTask.value?.cancel()
        }
    }
}

// MARK: - Wrapper
private final class Wrapper<Wrapped> {
    var value: Wrapped
    init(_ value: Wrapped) { self.value = value }
}
